### ISSUE TITLE
Move from JUnit4 to JUnit5

### ISSUE THREAD

**Issue by WhosNickDoglio** [WhosNickDoglio/Notes#32]

**Comment by maaudrana** [comment]
Playstore  link broken @WhosNickDoglio

**Comment by WhosNickDoglio** [comment]
> Playstore link broken @WhosNickDoglio

Hey @maaudrana 

Thanks for pointing this out. I've just submitted a new build to the Play Store which should fix the link. :)

**Comment by maaudrana** [comment]
Ok but showing  this is not available  in my country

**Comment by WhosNickDoglio** [comment]
> Ok but showing this is not available in my country

Hey @maaudrana 

The app itself is more just for demo purposes and for me to play around with different ideas but if you're interested it downloading I would be happy to make it available in your country, which country is that?

**Comment by maaudrana** [comment]
Its Bangladesh

**Comment by WhosNickDoglio** [comment]
> Its Bangladesh

Okay. I've updated it to make it available in Bangladesh, it could take a few hours for it to reflect in the Google Play store though.

**Comment by maaudrana** [comment]
Oh,Thanks for Response ♥️♥️
